import SideNavbarMain from "@/components/SideNavbar/SideNavbarMain";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderMain from "@/components/Header/HeaderMain";
import FooterMain from "@/features/footer/FooterMain";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="flex">
          <SideNavbarMain />
          <main className="flex-1 min-h-screen bg-[#1C2E3D] overflow-hidden">
            <HeaderMain />
            <div className="transition-all duration-300 py-[16px] px-[8px] lg:px-[8rem] xl:px-[16rem]">
              {children}
            </div>
            <FooterMain />
          </main>
        </div>
      </body>
    </html>
  );
}
